---
##
 # Copyright OpenSearch Contributors
 # SPDX-License-Identifier: Apache-2.0
##

# configuration file for the notifications plugin
opensearch.notifications:
  general:
    operationTimeoutMs: 60000 # 60 seconds, Minimum 100ms
    defaultItemsQueryCount: 100 # default number of items to query
    filterSendByBackendRoles: false # Does sendNotification needs to validate user's backend roles
